=== Ofeitus/BSUIR-WebTech-Archive/src/main/resources/db.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="archive">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="students">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="student" maxOccurs="unbounded" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:all maxOccurs="1" minOccurs="1">
                                        <xsd:element type="xsd:date" name="dateOfBirth"/>
                                        <xsd:element type="xsd:string" name="name"/>
                                        <xsd:element type="xsd:string" name="address"/>
                                        <xsd:element type="xsd:float" name="averageGrade"/>
                                    </xsd:all>
                                    <xsd:attribute type="xsd:ID" name="id" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Ofeitus/BSUIR-WebTech-Archive/src/main/resources/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<archive xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="db.xsd">
    <students>
        <student id="s0">
            <dateOfBirth>2001-04-30</dateOfBirth>
            <name>Tim</name>
            <address>Лещинского, 7, 180</address>
            <averageGrade>8.9</averageGrade>
        </student>
        <student id="s1">
            <name>Max</name>
            <dateOfBirth>2020-04-30</dateOfBirth>
            <address>Лещинского, 7, 360</address>
            <averageGrade>1.9</averageGrade>
        </student>
    </students>
</archive>
